Milestone 1: Mobile Version
JEFFKAY16/Portfolio-Website pull request #2
Opened 2021-09-16 15:53 UTC by JEFFKAY16

## Milestone 1: Set up and Mobile Version- Add Work and About Me Sections

In this project, I did the following:

- Added work and about me section to my portfolio website.
- Added HTML markup in in the HTML file.
- Added styles to the HTML markup in the CSS file.

2021-09-16 19:18 UTC, wandji20 requested changes
Hello, @JEFFKAY16 
-----
Great :muscle:  job :raised_hands:  implementing most of the requirements for this project.
However, there are a few issues you need to address to have this project approved.
## To Highlight! :clap:  :green_circle: 

:heavy_check_mark: Linter checks are passing
:heavy_check_mark: Descriptive commit messages

## Status: Require Changes :recycle: :red_circle: 
Please check the comments below and under the review and make all required changes.
[Optional] comments are not required to mark this project approved

- [ ] It will be nice to proofread your README and use tools like [grammarly](https://www.grammarly.com/grammar-check) to catch typos.
## Optional
-[ optional ]  Your app has a horizontal overflow. It will be nice to fix this and give it a better UI/UX.

**Happy coding :computer:** 
**_Do not hesitate to make comments in this PR in case of doubts._**
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 19:18 UTC, wandji20 commented on index.html
> +  <div class="works-section">
- [ ] It will be nice to use the semantic "section" tag instead of a div.

2021-09-16 19:18 UTC, wandji20 commented on styles.css
> +}
- [ ] We should align the content of the project with flexbox.

2021-09-16 19:18 UTC, wandji20 commented on index.html
> +        </div>
- [ ] It is better to put your project technologies in a "ul" and each of them in a "li" instead of the more generic "div".

2021-09-16 19:18 UTC, wandji20 commented on index.html
> +  <div class="about-me-section">
- [ ] It will be nice to use the semantic "section" tag instead of the generic "div" tag.

2021-09-16 19:18 UTC, wandji20 commented on styles.css
> +.card-tags .item1 {
- [ ] It will be nice to improve technology styling ie. Active, Hover, and Pressed. Currently, they appear as plain text.

2021-09-16 19:18 UTC, wandji20 commented on styles.css
> +.about-me-section {
- [ ] Our about me section has no background image. You can add that.

- [ ] It will be nice to use CSS flexbox to align the content of this section.

2021-09-16 19:18 UTC, wandji20 commented on index.html
> +          </div>
- [ ] It will be better to wrap our technologies in a "ul" tag and each technology in a "li" tag.

2021-09-16 19:18 UTC, wandji20 commented on index.html
> +  </div>
- [ ] It will be nice to place all projects in a container and give the container the appropriate style.

2021-09-16 19:18 UTC, wandji20 commented on styles.css
> +.project-cards {
- [ ] It will be nice to align the content of each project with flexbox.

2021-09-16 19:36 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @JEFFKAY16 , You did a great job so far 👏🏼 👏🏼 

- You did a good job in following the design

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-16 19:36 UTC, safafa commented on index.html
> +  <div class="works-section">
- [ ] I think it's better to replace the `div` tag with the HTML semantic tag `section` for the works-section to make your page more semantically correct.

2021-09-16 19:36 UTC, safafa commented on index.html
> +        </div>
- [ ] For the list of technologies for each project, you should use the list `<ul>` tag and put each technology in a `<li>`. Kindly make the change in all the project cards.

2021-09-16 19:36 UTC, safafa commented on index.html
> +  <div class="about-me-section">
- [ ] Kindly replace the div with a section tag for the same reason I cited before.

2021-09-16 19:36 UTC, safafa commented on index.html
> +            <div class="two-flex">
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") should be in a ul, each of them in a li, and The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list ul and each of them a li. Kindly make this change

2021-09-16 19:36 UTC, safafa commented on index.html
> +    <h1>My Recent<br>Works</h1>
- [ ] Kindly add the missing bar to make it look like the original design.
![image](https://user-images.githubusercontent.com/43698511/133674725-565722e7-1ebc-49bd-b2c8-81c3cbeee3fe.png)

2021-09-17 08:46 UTC, safafa commented
Hello, @JEFFKAY16. You can ignore the last review and only take the first one in consideration.

2021-09-17 09:11 UTC, JEFFKAY16 commented on styles.css
> +.about-me-section {
- [ ] The about me section does have a background image. Please check and confirm.

2021-09-17 09:28 UTC, wandji20 commented on styles.css
> +.about-me-section {
- [ ] Your right. You have implemented a background image in the "about-text", yet you are expected to set the background image to the whole section
![screeen](https://user-images.githubusercontent.com/65476715/133760163-e115308b-e2de-4277-88b9-356c4f5403af.png)
.

2021-09-17 09:35 UTC, JEFFKAY16 commented on styles.css
> +.about-me-section {
Okay got that. Thanks, I'll do the needful

2021-09-18 00:24 UTC, mke2111 approved these changes
### Hi @JEFFKAY16, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-18 00:29 UTC, merged